version: "3"
services:
  web:
    image: amigadev/amigadev.com
    restart: always
    labels:
      - "traefik.http.routers.amigadev.rule=Host(`amigadev.local`)"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik_default
